services:
  clip-srt:
    build: .
    container_name: clip-srt
    restart: always
    env_file:
      - .env
    volumes:
      - ./whisper_model:/app/whisper_model
      - ./archive:/app/archive
      - ./cache:/app/cache
      - ./service.log:/app/service.log

networks:
  default:
    name: vpn
    external: true